<?php

namespace Proxy\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dispatch extends \Dispatch implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'updated_at' => [parent::class, 'updated_at', null],
        'created_at' => [parent::class, 'created_at', null],
        'end_date' => [parent::class, 'end_date', null],
        'id' => [parent::class, 'id', null],
        'is_complete' => [parent::class, 'is_complete', null],
        'patron' => [parent::class, 'patron', null],
        'proxy' => [parent::class, 'proxy', null],
        'route' => [parent::class, 'route', null],
        'start_date' => [parent::class, 'start_date', null],
        'updated_at' => [parent::class, 'updated_at', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
